services:
  db:
    container_name: postgres_db
    image: postgres:16.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    networks:
      - django_net
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    entrypoint: ["./entrypoint.sh"]
    command: ["gunicorn", "crm.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: crm_db
      DB_USER: postgres
      DB_PASS: admin
    depends_on:
      - db
    networks:
      - django_net
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx/error:/var/log/nginx/error
      - ./logs/nginx/access:/var/log/nginx/access
      - ./staticfiles:/usr/share/nginx/html/css
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django_net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - django_net

networks:
  django_net:
    driver: bridge
