# Generated by Django 5.1.1 on 2024-09-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование')),
                ('promotion_channel', models.CharField(blank=True, max_length=50, verbose_name='Канал продвижения')),
                ('advertising_budget', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Рекламный бюджет')),
                ('advertised_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Представляемая услуга')),
            ],
            options={
                'verbose_name_plural': 'Маркетинг',
            },
        ),
    ]
