# Generated by Django 5.1.1 on 2024-09-19 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допустимо до 11 цифр.", regex='^\\+?1?\\d{8,11}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('promotion_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads', verbose_name='Название рекламной кампании')),
            ],
        ),
    ]
