# Generated by Django 5.1.1 on 2024-09-27 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leads_first_name_alter_leads_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+799999999'. Допустимо до 12 цифр.", regex='^\\+?1?\\d{8,12}$')], verbose_name='Номер телефона'),
        ),
    ]
