# Generated by Django 5.1.1 on 2024-09-27 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leads_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+799999999'. Допустимо до 16 цифр.", regex='^\\+?1?\\d{8,16}$')], verbose_name='Номер телефона'),
        ),
    ]
