# Generated by Django 5.1.1 on 2024-09-19 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='Название')),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения контракта')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала действия контракта')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания действия контракта')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('service_provided', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Представляемая услуга')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
