# Generated by Django 5.1.1 on 2024-09-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
    ]
